### ISSUE TITLE
Handling object ids and attributes

### ISSUE THREAD

**Issue by rclark** [mapbox/minjur#11]
Some other systems we use to build geojson from openstreetmap data end up presenting a geojson object like this:

``` json
{
  "type": "Feature",
  "id": "node!291496331!3",
  "properties": {
    "is_in": "ACT, Australia",
    "name": "Theodore",
    "place": "suburb",
    "osm:type": "node",
    "osm:id": 291496331,
    "osm:version": 3,
    "osm:changeset": 36291100,
    "osm:timestamp": 1451605692000,
    "osm:uid": 609921,
    "osm:user": "JStar73"
  },
  "geometry": {
    "type": "Point",
    "coordinates": [
      149.1215891,
      -35.4494709
    ]
  }
}
```
- top-level `id` is `type ! id ! version`
- attributes are included in the properties object, prefixed with `osm:`

Could this also become the default behavior for minjur, possibly with an option to set your own attribute prefix? More specifically my question is -- would this change be acceptable for qa-tiles?

cc @joto @mikelmaron @MateoV @geohacker

**Comment by mikelmaron** [comment]
It would be best to be consistent with how we translate OSM to GeoJSON across systems, for muscle memory and potential of shared libraries. I prefer `osm:` notation.

@geohacker @tcql how much pain to update osmlint and other OSMQATiles processors to handle the change? Doesn't look too widespread actually

Here's a couple searches to have find code that references the current format.
- https://github.com/search?utf8=%E2%9C%93&q=user%3Aosmlab+%22_user%22&type=Code&ref=searchresults
- https://github.com/search?utf8=%E2%9C%93&q=user%3Aosmlab+%22_timestamp%22&type=Code&ref=searchresults

**Comment by rclark** [comment]
@joto the `_osm_area_id` properties also present a bit of a problem. We'll need to be able to map these back to relation or way ids for the feature's top-level `id` attribute.

**Comment by geohacker** [comment]
I'd love if this can become consistent. Changes in osmlint is minimal.

**Comment by joto** [comment]
I know of two long-standing precedences for the prefix: Osm2pgsql uses [`osm_` prefix](https://wiki.openstreetmap.org/wiki/Osm2pgsql#Special_.27tags.27), XAPI uses [`@` prefix](http://wiki.openstreetmap.org/wiki/Xapi#Tags). I like the `@`, because it is short and the special character makes it quite obvious that something special is going on here. The `@` has the added bonus that it comes before the letters in ASCII or Unicode, so those properties will be sorted before the other tags. There is currently only a single tag in the OSM database with a `@` in it and it is obvious rubbish and I don't see we'll ever have "legal" tag keys starting with `@`.

The area id is there to have a unique ID for areas. But this id is generated from the relation or way id the area was created from, we can always get this back if we want to. I tend to think of areas as objects in their own right:

`"id"="area!100", "properties": { "@type"="area", "@id": 100, "@from_way":50, ...}`

But you can also see them as:

`"id"="area!100", "properties": { "@type"="way", "@id": 50, ...}`

In any case the "id" property can't be "way!50" for this area, because there will be another object with that ID containing a LineString.

Incidentally, I think your IDs of the form `node!1234!56` could be shortened to `n1234.56` or so. And while we are at it, I am not sure about the use of the version number here. If your intention is to have different IDs when something changes in an object, this version number is not enough. If a node changes inside a way, but the way doesn't change, the result is a different LineString but with the same ID. The same logic applies to areas.

**Comment by rclark** [comment]
I'm generally inclined to maintain the geojson feature's `id` as a solid pointer to the openstreetmap object that it was built from. I understand the reasoning for the area construct, but to me the correlation with the real data is more important.

Obviously, the generation of a linestring and a polygon for a single openstreetmap object makes that a problem. I believe that all the same functionality discussed in #9 would also be desirable in the context of areas and multipolygons. We can continue that discussion over there.

**Comment by joto** [comment]
See http://wiki.openstreetmap.org/wiki/Overpass_turbo/GeoJSON for another precedence using `@`.

**Comment by rclark** [comment]
`@` sounds like a great default option for minjur, where speed and output size are probably the driving forces.

But let's curb any more discussion about what's the "best" prefix -- this is a decision best left to the implementing party or organization. Instead, let's make sure to add a `--prefix` flag that allows the caller to override the prefix based on their application's needs.

I'm also happy to curb `id` specific discussions until we reach a decision on #9.

**Comment by joto** [comment]
Aren't we the "implementing party or organization"?

In my opinion the `id` is independent on #9. We can not make sure that we will only have either a LineString or an Area. There are cases where we need both (my stock example is a closed way that is tagged has roundabout and as some kind of landuse). We might not do this now, or tomorrow, but some day we want to have this option, and by that time it might be difficult to change id format.

**Comment by rclark** [comment]
> Aren't we the "implementing party or organization"?

I'm considering this as a more broadly useful tool across different systems. Let's move past comparing our opinions on what's best to implementing a `--prefix` for attributes. I would love to take this on as an introduction to working on this project. 

> We can not make sure that we will only have either a LineString or an Area.

That's great for discussion in #9 -- let's keep these separate.

**Comment by joto** [comment]
@rclark Feel free to send me a pull request on the `--prefix` thing.

There is another difference in the current code that's not handled by prefix. It generates `_osm_node_id`, `_osm_way_id`, `_osm_area_id` "keys", not "id" and a separate "type".

**Comment by rclark** [comment]
Given that the top-level `id` property will remain the unique, osmium-assigned id (node, way, area), how would you feel about providing `{prefix}id` and `{prefix}type` in the geojson's properties object, as the backpointer to the original openstreetmap feature?

**Comment by joto** [comment]
@rclark sounds good
