### ISSUE TITLE
Test minjur-mp against HEAD libosmium

### ISSUE THREAD

**Issue by springmeyer** [mapbox/minjur#17]
Latest (unreleased) libosmium has much improved multipolygon assembly code. It is better at detecting invalid polygons, better at reporting them, and much faster than the previous code.

Before releasing latest libosmium @joto needs the tires to be kicked on the code to look for bugs or discrepancies.

Todo:
- [ ] create a minjur branch that builds against libosmium latest
- [ ] create some mason packages (if useful)
- [ ] test planet imports, do some basic QA on results

@aaronlidman can you lead this out?

/cc @rclark @joto
- refs https://github.com/osmcode/node-osmium/issues/80

**Comment by aaronlidman** [comment]
👍 Sounds good.
- @MateoV added support to the osm-qa-tiles a few weeks ago and tracked performance.
- @Rub21 has also been testing out he resulting vector tiles and also ran into issues.

I'll run out who should update and recheck things and see if that helps.

**Comment by springmeyer** [comment]
Any updates on this @aaronlidman?

**Comment by rclark** [comment]
I picked up looking at this with the intention of 
a) running minjur-mp on the planet to assess performance, while
b) writing geometry errors to a file, in order to
c) run `oat_problem_report` on each invalid relations, so that I can
d) put together a to-fix CSV to hand off to the data team.

@joto I noticed that the output ids in the error file are area ids, not way or relation ids. My intention was to fetch each invalid relation as XML from the v0.6 API and run `oat_problem_report` on each of them. Do you have any better suggestion, or could the error file output the original way/relation ids?

**Comment by rclark** [comment]
Performance improvement is striking -- on an r3.2xlarge instance:

```
time minjur-mp -e ./errors -n dense ./planet.osm.pbf > /dev/null
Using the 'dense_mmap_array' location store. Use -l or -n to change this.
Reading from './planet.osm.pbf'...
Pass 1...
Pass 1 done
Pass 2...
Pass 2 done
Number of geometry errors (not written to output): 25631
Done.

real    65m57.097s
user    97m37.824s
sys     3m52.143s
```

Previous runs on old libosmium are on the order of 2.5-3 hours. This is a great improvement.

There are 14,623 invalid ways (1669 of these are not polygons) and 11,008 invalid relations.

**Comment by joto** [comment]
Instead of using `oat_problem_report` and then reading in the spatialite data it generates and converting it to GeoJSON, we could directly generate JSON using a suitable implementation in C++. All you have to do is create a class deriving from [`problem_reporter`](https://github.com/osmcode/libosmium/blob/master/include/osmium/area/problem_reporter.hpp) which does that and plug it into the multipolygon assembler instead of the one generating the OGR reports.

And I am not sure why you want to fetch the invalid areas from the API? Minjur already has all the data, so could report this directly.

**Comment by joto** [comment]
@rclark  `oat_problem_report` and `oat_create_areas` report the problematic way or relation ID in the `obj_id` attribute and either `w` or `r` in the `obj_type` attribute. If you are seeing an area ID somewhere, that's a bug.

**Comment by rclark** [comment]
I am currently exploring two avenues for detecting / analyzing invalid relations -- one is to look at the minjur error report, and the other is to report issues as they are generated by changes to OSM by tracking what node-osmium rejects in dynamosm.

What I'd like to do in both cases is output the XML that was considered invalid, then feed this to osm_problem_report, or better yet, as you say, a different problem_reporter implementation that tailors its output specifically to whatever format it makes sense for us to help prioritize OSM fixes.

As there's still a lot of discussion with everybody about what that format really is, this Frankenstein approach is just a way to start trying things using the existing outputs and tools. I'm interested in a better solution but still feel like I don't have a solid idea of what that output should look like. https://github.com/mapbox/dynamosm-invalid-relations/issues/1 for more discussion there.

btw the area ids are in the minjur error file, not in any of the OAT outputs.

**Comment by joto** [comment]
Ah, okay. You can always get the original IDs back from an area ID with this formula: `orig_id = int(area_id / 2);` If the area ID is even, it was created from a way, if it is odd, it was create from a relation.

**Comment by joto** [comment]
This seems to be stale. Closing.
