### ISSUE TITLE
Option to output "FeatureCollection" GeoJSON instead of "Feature" per line 

### ISSUE THREAD

**Issue by artemp** [mapbox/minjur#23]
In some cases (for example creating test GeoJSON data from OSM) it would be useful to have an option to output "FeatureCollection" GeoJSON e.g

```json
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [123,345]
      }
   },
   {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [456,789]
      }
    }
  ]
}
```

In case anyone interested, it can be accomplished using current "Feature" per line output and some post editing (see script below) but having this as an option would still be useful.

#### osm2geojson.sh

```bash

#!/bin/bash

MINJUR=minjur

if [[ -z "$1" || -z "$2" ]]; then
    echo Usage: $0 "<input.pbf> <output.geojson>"
    exit
fi

TEMPFILE="$2.tmp"
TEMPFILE2="$2.tmp2"

$MINJUR -p -a "_" $1 > $TEMPFILE
sed "s/$/,/g" $TEMPFILE > $TEMPFILE2
rm $TEMPFILE
sed '$s/,$//' $TEMPFILE2 > $TEMPFILE
rm $TEMPFILE2
sed -e $'1i\\\n{\"type\": \"FeatureCollection\",\"features\": [' -e $'$a\\\n]}' $TEMPFILE > $2
rm $TEMPFILE
```

**Comment by springmeyer** [comment]
> but having this as an option would still be useful

👍 I've also needed to hack this into minjur before. Would be great to have it as an option (default off).

**Comment by joto** [comment]
The upcoming `osmium export` command (#28) supports three different formats:
* plain GeoJSON
* GeoJSON Text Sequences (RFC8142)
* GeoJSON Text Sequences, but without the RS (this is the format that minur uses)

Choice of formats is based on file name suffix or command line options.

Please have a look whether this does all it needs to do.

Because minjur is being phased out, this will not be changed in minjur any more.

**Comment by springmeyer** [comment]
Thanks for the details @joto - sounds great. I'll now close this. @artemp please test with the new osmium-tool per https://github.com/mapbox/minjur/issues/28#issuecomment-298798206
